// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appName => 'DishaAjyoti';

  @override
  String get appTagline => 'Career & Life Guidance';

  @override
  String get splashLoading => 'Loading...';

  @override
  String get onboardingSkip => 'Skip';

  @override
  String get onboardingBack => 'Back';

  @override
  String get onboardingNext => 'Next';

  @override
  String get onboardingGetStarted => 'Get Started';

  @override
  String get onboardingTitle1 => 'Career Guidance Made Simple';

  @override
  String get onboardingSubtitle1 => 'Discover Your Path';

  @override
  String get onboardingDesc1 =>
      'Get personalized career guidance based on ancient wisdom and modern insights';

  @override
  String get onboardingTitle2 => 'Palmistry Analysis';

  @override
  String get onboardingSubtitle2 => 'Read Your Palm';

  @override
  String get onboardingDesc2 =>
      'Unlock the secrets hidden in your palm lines and discover your life\'s journey';

  @override
  String get onboardingTitle3 => 'Vedic Jyotish';

  @override
  String get onboardingSubtitle3 => 'Astrological Insights';

  @override
  String get onboardingDesc3 =>
      'Comprehensive Vedic astrology reports based on your birth chart';

  @override
  String get onboardingTitle4 => 'Numerology';

  @override
  String get onboardingSubtitle4 => 'Power of Numbers';

  @override
  String get onboardingDesc4 =>
      'Discover your life path through the ancient science of numerology';

  @override
  String get onboardingTitle5 => 'Personalized Reports';

  @override
  String get onboardingSubtitle5 => 'AI-Powered Analysis';

  @override
  String get onboardingDesc5 =>
      'Get detailed PDF reports generated by advanced AI technology';

  @override
  String get onboardingTitle6 => 'Ready to Begin';

  @override
  String get onboardingSubtitle6 => 'Start Your Journey';

  @override
  String get onboardingDesc6 =>
      'Join thousands of users who have found clarity and direction';

  @override
  String get welcomeBack => 'Welcome Back';

  @override
  String get signInToContinue => 'Sign in to continue your journey';

  @override
  String get createAccount => 'Create Account';

  @override
  String get signUpToStart => 'Sign up to start your journey';

  @override
  String get email => 'Email';

  @override
  String get enterEmail => 'Enter your email';

  @override
  String get password => 'Password';

  @override
  String get enterPassword => 'Enter your password';

  @override
  String get confirmPassword => 'Confirm Password';

  @override
  String get reEnterPassword => 'Re-enter your password';

  @override
  String get fullName => 'Full Name';

  @override
  String get enterFullName => 'Enter your full name';

  @override
  String get forgotPassword => 'Forgot Password?';

  @override
  String get login => 'Login';

  @override
  String get signUp => 'Sign Up';

  @override
  String get signIn => 'Sign In';

  @override
  String get or => 'OR';

  @override
  String get continueWithGoogle => 'Continue with Google';

  @override
  String get continueWithApple => 'Continue with Apple';

  @override
  String get dontHaveAccount => 'Don\'t have an account? ';

  @override
  String get alreadyHaveAccount => 'Already have an account? ';

  @override
  String get agreeToTerms => 'I agree to the ';

  @override
  String get termsAndConditions => 'Terms & Conditions';

  @override
  String get and => ' and ';

  @override
  String get privacyPolicy => 'Privacy Policy';

  @override
  String get acceptTermsError =>
      'Please accept the Terms & Conditions to continue';

  @override
  String get loginSuccess => 'Login successful!';

  @override
  String loginFailed(String error) {
    return 'Login failed: $error';
  }

  @override
  String registrationFailed(String error) {
    return 'Registration failed: $error';
  }

  @override
  String get googleSignInComingSoon => 'Google Sign-In coming soon';

  @override
  String get appleSignInComingSoon => 'Apple Sign-In coming soon';

  @override
  String get termsComingSoon => 'Terms & Conditions screen coming soon';

  @override
  String get privacyComingSoon => 'Privacy Policy screen coming soon';

  @override
  String get resetPassword => 'Reset Password';

  @override
  String get resetPasswordDesc =>
      'Enter your email address and we\'ll send you instructions to reset your password';

  @override
  String get sendResetLink => 'Send Reset Link';

  @override
  String get backToLogin => 'Back to Login';

  @override
  String get resetLinkSent =>
      'Password reset link sent! Please check your email.';

  @override
  String resetFailed(String error) {
    return 'Failed to send reset link: $error';
  }

  @override
  String get profileSetup => 'Profile Setup';

  @override
  String stepXOfY(int current, int total) {
    return 'Step $current of $total';
  }

  @override
  String get birthDetails => 'Birth Details';

  @override
  String get careerInformation => 'Career Information';

  @override
  String get yourChallenges => 'Your Challenges';

  @override
  String get dateOfBirth => 'Date of Birth';

  @override
  String get selectDate => 'Select date';

  @override
  String get timeOfBirth => 'Time of Birth';

  @override
  String get selectTime => 'Select time';

  @override
  String get placeOfBirth => 'Place of Birth';

  @override
  String get enterPlaceOfBirth => 'Enter place of birth';

  @override
  String get currentCareer => 'Current/Past Career';

  @override
  String get enterCareer => 'Enter your current or past career';

  @override
  String get careerGoals => 'Career Goals';

  @override
  String get enterGoals => 'What are your career goals?';

  @override
  String get currentChallenges => 'Current Challenges';

  @override
  String get enterChallenges => 'What challenges are you facing?';

  @override
  String get privacyNotice =>
      'Your information is kept private and secure. We use it only to generate personalized reports.';

  @override
  String get back => 'Back';

  @override
  String get next => 'Next';

  @override
  String get complete => 'Complete';

  @override
  String get profileSaved => 'Profile saved successfully!';

  @override
  String profileSaveFailed(String error) {
    return 'Failed to save profile: $error';
  }

  @override
  String get home => 'Home';

  @override
  String get services => 'Services';

  @override
  String get reports => 'Reports';

  @override
  String get profile => 'Profile';

  @override
  String get welcomeBackComma => 'Welcome back,';

  @override
  String get exploreServices => 'Explore Services';

  @override
  String get reportsLabel => 'Reports';

  @override
  String get spent => 'Spent';

  @override
  String get featuredServices => 'Featured Services';

  @override
  String get viewAll => 'View All';

  @override
  String get ourServices => 'Our Services';

  @override
  String get chooseService => 'Choose the service that best fits your needs';

  @override
  String get myReports => 'My Reports';

  @override
  String get viewDownloadReports => 'View and download your generated reports';

  @override
  String get noReportsYet => 'No Reports Yet';

  @override
  String get noReportsDesc =>
      'You haven\'t generated any reports yet.\\nExplore our services to get started!';

  @override
  String get browseServices => 'Browse Services';

  @override
  String get profileInformation => 'Profile Information';

  @override
  String get phone => 'Phone';

  @override
  String get totalReports => 'Total Reports';

  @override
  String get totalSpent => 'Total Spent';

  @override
  String get settings => 'Settings';

  @override
  String get managePreferences => 'Manage your preferences';

  @override
  String get helpAndSupport => 'Help & Support';

  @override
  String get getHelp => 'Get help with your account';

  @override
  String get about => 'About';

  @override
  String get learnMore => 'Learn more about DishaAjyoti';

  @override
  String get logout => 'Logout';

  @override
  String get logoutConfirmTitle => 'Logout';

  @override
  String get logoutConfirmMessage =>
      'Are you sure you want to logout from your account?';

  @override
  String get cancel => 'Cancel';

  @override
  String get helpComingSoon => 'Help & Support coming soon';

  @override
  String get aboutComingSoon => 'About screen coming soon';

  @override
  String openingReport(String fileName) {
    return 'Opening report: $fileName';
  }

  @override
  String get reportGenerating =>
      'Report is still being generated. Please check back later.';

  @override
  String get reportFailed =>
      'Report generation failed. Please contact support.';

  @override
  String get ok => 'OK';

  @override
  String get palmistryReading => 'Palmistry Reading';

  @override
  String get palmistryDesc =>
      'Get insights into your life through palm reading';

  @override
  String get vedicJyotishAnalysis => 'Vedic Jyotish Analysis';

  @override
  String get vedicJyotishDesc => 'Comprehensive Vedic astrology report';

  @override
  String get numerologyReport => 'Numerology Report';

  @override
  String get numerologyDesc => 'Discover your life path through numbers';

  @override
  String get getNow => 'Get Now';

  @override
  String get detailedPalmAnalysis => 'Detailed palm analysis';

  @override
  String get lifeLineReading => 'Life line reading';

  @override
  String get careerGuidance => 'Career guidance';

  @override
  String get birthChartAnalysis => 'Birth chart analysis';

  @override
  String get planetaryPositions => 'Planetary positions';

  @override
  String get futurePredictions => 'Future predictions';

  @override
  String get lifePathNumber => 'Life path number';

  @override
  String get destinyNumber => 'Destiny number';

  @override
  String get luckyNumbers => 'Lucky numbers';

  @override
  String get estimatedTime24 => '24 hours';

  @override
  String get estimatedTime48 => '48 hours';

  @override
  String get estimatedTime12 => '12 hours';

  @override
  String get payment => 'Payment';

  @override
  String get orderSummary => 'Order Summary';

  @override
  String get serviceName => 'Service Name';

  @override
  String get price => 'Price';

  @override
  String get proceedToPayment => 'Proceed to Payment';

  @override
  String get paymentSuccess => 'Payment successful!';

  @override
  String get paymentFailed => 'Payment failed. Please try again.';

  @override
  String get processingPayment => 'Processing payment...';

  @override
  String get reportReady => 'Ready';

  @override
  String get reportGeneratingStatus => 'Generating';

  @override
  String get reportFailedStatus => 'Failed';

  @override
  String get downloadReport => 'Download Report';

  @override
  String get viewReport => 'View Report';

  @override
  String reportSize(String size) {
    return '$size MB';
  }

  @override
  String get notifications => 'Notifications';

  @override
  String get noNotifications => 'No notifications yet';

  @override
  String get noNotificationsDesc =>
      'You\'ll see notifications here when you have updates';

  @override
  String get markAllRead => 'Mark all as read';

  @override
  String get newNotification => 'New';

  @override
  String get settingsTitle => 'Settings';

  @override
  String get general => 'General';

  @override
  String get notificationSettings => 'Notification Settings';

  @override
  String get enableNotifications => 'Enable Notifications';

  @override
  String get receiveUpdates => 'Receive updates about your reports';

  @override
  String get language => 'Language';

  @override
  String get selectLanguage => 'Select Language';

  @override
  String get english => 'English';

  @override
  String get hindi => 'हिंदी';

  @override
  String get aboutApp => 'About App';

  @override
  String get version => 'Version';

  @override
  String get termsOfService => 'Terms of Service';

  @override
  String get privacyPolicyTitle => 'Privacy Policy';

  @override
  String get contactSupport => 'Contact Support';

  @override
  String get settingsSaved => 'Settings saved successfully';

  @override
  String get errorOccurred => 'An error occurred';

  @override
  String get tryAgain => 'Try Again';

  @override
  String get networkError => 'Network error. Please check your connection.';

  @override
  String get serverError => 'Server error. Please try again later.';

  @override
  String get validationError => 'Please check your input and try again.';

  @override
  String get sessionExpired => 'Your session has expired. Please login again.';

  @override
  String get fieldRequired => 'This field is required';

  @override
  String get invalidEmail => 'Please enter a valid email address';

  @override
  String get invalidPassword =>
      'Password must be at least 8 characters with uppercase, lowercase, and number';

  @override
  String get passwordMismatch => 'Passwords do not match';

  @override
  String get invalidPhone => 'Please enter a valid phone number';

  @override
  String get invalidName => 'Please enter a valid name';

  @override
  String get loading => 'Loading...';

  @override
  String get save => 'Save';

  @override
  String get delete => 'Delete';

  @override
  String get edit => 'Edit';

  @override
  String get close => 'Close';

  @override
  String get confirm => 'Confirm';

  @override
  String get yes => 'Yes';

  @override
  String get no => 'No';

  @override
  String get search => 'Search';

  @override
  String get filter => 'Filter';

  @override
  String get sort => 'Sort';

  @override
  String get refresh => 'Refresh';

  @override
  String get retry => 'Retry';

  @override
  String get submit => 'Submit';

  @override
  String get continueButton => 'Continue';

  @override
  String get done => 'Done';
}
